### PR TITLE
Paths config (round 2)

### PR DESCRIPTION
**Pull request by timrwood**
This is a followup PR to #11. /cc @isochronous

This adds the ability to start an include path with an `@base` segment.

``` js
include('@base/scripts/app.js');
```

Now, rather than the include statement being relative to the current file, it will be relative to the current working directory.

``` js
// cwd: /Users/timrwood/

// file: /Users/timrwood/scripts/a.js
include('./c.js');     //Users/timrwood/scripts/c.js

// file: /Users/timrwood/scripts/b.js
include('@base/c.js'); //Users/timrwood/c.js
```

Additionally, users can define their own mappings. These paths are all resolved relative to the current working directory.

``` js
includer(file, {
  paths : {
    libs : 'project/source/libs',
    app : 'project/source/js'
  }
}, done);
```

These are used the same way as `@base`.

``` js
// cwd: /Users/timrwood/my-project

include('@libs/jquery/jquery');         //Users/timrwood/my-project/project/source/libs/jquery/jquery.js
include('@libs/handlebars/handlebars'); //Users/timrwood/my-project/project/source/libs/handlebars/handlebars.js
include('@libs/ember/ember');           //Users/timrwood/my-project/project/source/libs/ember/ember.js
var App = Ember.Application.create();
include('@app/router');                 //Users/timrwood/my-project/project/source/js/router.js
include('@app/routes/*');               //Users/timrwood/my-project/project/source/js/routers/*.js
```

If needed, it is also possible to override `@base`.

``` js
includer(file, {
  paths : {
    base : '../new/path/to/base/'
  }
}, done);
```

### CODE REVIEW

**Comment by isochronous** [comment]
Looks awesome man! I really appreciate your working with me on this. It's going to be really useful to more than one project I'm working on.

**Comment by isochronous** [comment]
This is fantastic!  Can you update the npm package?  (And the gulp-includer package to use the new version?)

**Comment by timrwood** [comment]
Yep, I just need to write up some documentation (probably just copy+paste what is in the description of this PR) and then I'll publish a new version of this and gulp-includer.

**Comment by isochronous** [comment]
You are the man, sir!  It's always a pleasure working with someone open to suggestions and improvements, especially when I get to learn something along the way.

**Comment by timrwood** [comment]
No problem! Thanks for the suggestion!

**Comment by timrwood** [comment]
@isochronous, published `0.1.0` of both includer and gulp-includer.

Do you mind reading over https://github.com/timrwood/includer#paths and making sure I didn't miss anything?

**Comment by isochronous** [comment]
I'd mention that the base mapping can be overridden via the paths config, but other than that, looks good to me!

**Comment by isochronous** [comment]
Actually, there is one more consideration - you say that path aliases are relative to the CWD - is that true, or are they relative to whatever `@Base` is set to?  I'd argue for the latter rather than the former.

**Comment by timrwood** [comment]
The mappings are always relative to the cwd, not `@base`. I think this is less confusing than having the aliases relative to `@base`.

Because the entry point path (the first argument passed to includer) is relative to the cwd, I think keeping all paths relative to the cwd is the most intuitive.

``` js
// cwd root
// Everywhere a path is represented, it is relative to the same root.
includer('source/js/app.js', { paths : {
  lib:   'source/lib',
  other: 'other/folder'
}}, cb);

// base root
// @base is relative to the same root as source/js/app.js,
// but @lib and @other are relative to @base.
// Changes to base require changes to every other mapping.
includer('source/js/app.js', { paths : {
  base:  'source',
  lib:   'lib',            // actually source/lib
  other: '../other/folder' // actually other/folder
}}, cb);
```

If there are a lot of paths sharing a common root, it is pretty easy to just handle this with string concatenation.

``` js
// instead of using base as the root
includer('source/js/app.js', { paths : {
  base:  'source/scripts/vendor/libs/some/long/path',
  jquery:'jquery/dist',
  ember: 'ember'
}}, cb);

// just store the base in a variable
var base = 'source/scripts/vendor/libs/some/long/path/';
includer('source/js/app.js', { paths : {
  jquery : base + 'jquery/dist',
  ember  : base + 'ember'
}}, cb);
```

**Comment by isochronous** [comment]
Okay... well, in that case, is it possible to use an alias in another alias?  For example, this is a portion of my current paths config: 

``` js
    ScriptSrc                 : '@base/Scripts/src',
    Graph                     : '@base/Scripts/src/graph',
    Report                    : '@base/Scripts/src/report',
    Collectors                : '@base/Scripts/src/report/collectors',
    ReportTemplates           : '@base/Scripts/src/report/templates',
```

In my previous code, `@base` was kind of a special case that was handled separately from the other aliases, so this worked the way I wanted it to.  I noticed that your current logic is drastically different from my implementation, and you're definitely more comfortable with node paths than I am, so I can't tell for sure if what I have will still work or not.

**Comment by timrwood** [comment]
I wanted to avoid adding aliases in aliases as it kinda gets complex pretty quick.

For one thing, we would have to watch out for recursion.

``` js
paths = {
   a : '@b/a',
   b : '@c/b',
   c : '@a/c'
};
```

For your paths config, you should be able to drop `@base/` and everything should still work. If you are using gulp, I believe the cwd is always the directory that contains `gulpfile.js`.

You should also be able to do something like this in your config.

``` js
var ScriptSrc = 'Scripts/src/',
    Report    = ScriptSrc + 'report/';

paths = {
    ScriptSrc                 : ScriptSrc,
    Graph                     : ScriptSrc + 'graph',
    Report                    : Report,
    Collectors                : Report + 'collectors',
    ReportTemplates           : Report + 'templates'
}
```

If `Scripts` is not a sibling of `gulpfile.js`, you can change it to `var ScriptSrc = '../../Scripts/src/'` or whatever you need.

**Comment by isochronous** [comment]
Yeah, I wasn't really thinking that any alias in an alias would be a good
thing (in fact, I was definitely against it) but being able to redefine
base and use a different base URL in different gulp tasks would be handy.
 I'll try the string concatenation thing for now; if I wind up hating it I
can always fork the project - after all, that's half the point of open
source anyway.

**Comment by isochronous** [comment]
Will you go ahead and publish the new versions to npm today?

**Comment by timrwood** [comment]
Both were published yesterday. `includer@0.1.0` and `gulp-includer@0.1.0`.

**Comment by isochronous** [comment]
Sorry, I'm an idiot - you did what I was going to suggest (bumping the version to 0.1.0 rather than 0.0.4) without me even suggesting it.  Thanks man!

**Comment by timrwood** [comment]
No problem!

Yeah, I usually stick with [semver](http://semver.org/). Major bump for breaking changes, minor for new features, and patch for bugfixes.

**Pull request merged**
