### PR TITLE
Fix inconsistent path slashes breaking seen logic

### LINKED ISSUE #8: Infinite loop caused by recursive imports
Although the documentation lists `include('./*.js')` as a valid include pattern, when I attempt to use it, includer seems to enter an infinite loop and simply hangs until I Ctrl-C out of it.

Also, the NPM package seems to be out of date.  Even when I did a `npm install includer@0.0.2` I didn't get the code that's currently in the master branch, and there's not a version 0.0.3 either.  I had to manually save the files from github to get the latest version.

### PR DESCRIPTION
**Pull request by isochronous**
Fixes #8
On windows machines, globs return paths with backslashes, but filepaths
are represented with forward slashes.  This breaks the "seen" tracking,
as `d:\some\path` obviously won't match `d:/some/path`.  Use `path.resolve()`
in the File's `seen` method to normalize slashes in paths before
checking against the "seen" hash, and do the same in the GlobNode's
`findFiles` method.

### CODE REVIEW

**Comment by isochronous** [comment]
I tried to stick to your coding standards as defined in your .editorconfig file, btw - tab indentation and a blank line at the end of the files.

**Comment by timrwood** [comment]
Looks good, thanks!

**Comment by timrwood** [comment]
`includer@0.0.3` and `gulp-includer@0.0.3` are published to npm, let me know if you have any issues.

**Comment by isochronous** [comment]
Thanks man!

-----Original Message-----

**Pull request merged**
