### PR TITLE
Paths config

### PR DESCRIPTION
**Pull request by isochronous**
Wish  you had  a dev branch or something so I didn't have to submit this to master, but time to suck it up and show some confidence in my code I guess ;)

I'll change the path mapping logic to use the `@alias` format once I get back from lunch.

I still think there are good use cases for allowing users to change the baseUrl to something other than `cwd`, so maybe we could think of a different token to use for that reference than `:cwd`.  Maybe `:root` ?

### CODE REVIEW

**Comment by isochronous** [comment]
I guess I should mention this is an attempt to address #10.

In my latest commit, I changed the `~` symbol to `:base` instead (as the option I most often see used for things like this is `baseUrl`, and wanted to be consistent).  I also updated the logic to treat the `@` symbol as specifying that the path segment in question is a path mapping that's set via the options passed to includer.  The actual paths config, however, does not require the '@' symbol (and in fact will not work if present.)

For example, a file using a path mapping to include another file would do so like:

``` js
include('@Scriptsrc/myfile.js');
```

And in the options passed to includer, you'd define:

``` js
includer('main.js', {
    paths: {
        'Scriptsrc': ':base/Script/src'
    }
}, function (err, result) {
    // do something with the result
});
```

Again, the unit tests are failing because of inconsistent line endings between our platforms - I didn't want to add any new dependencies or anything for more flexible assertion libs, but I couldn't figure out how to fix the problem without just stripping out all line breaks, which would make the unit tests dealing with separators worthless.

**Comment by isochronous** [comment]
Sweet, I was able to at least get the Travis CI unit tests to pass, even if they fail on my local system.  You'd think they're take that kind of thing into account in the assert lib..

**Comment by timrwood** [comment]
Looking good, thanks for working on this!

I think we can simplify the api a bit though.

First, we can `path.resolve()` everything in `paths` to the cwd in the `File` constructor.

``` js
includer(file, {
  paths : {
    Scriptsrc : 'Script/src',
    baz       : 'test/fixtures/baz',
    aboveCwd  : '../other'
  }
}, cb);

// cwd = /Users/timrwood/includer/
File.paths === {
    Scriptsrc : '/Users/timrwood/includer/Script/src',
    baz       : '/Users/timrwood/includer/test/fixtures/pathMapping/B',
    aboveCwd  : '/Users/timrwood/other'
};
```

We can also add a default `@base` path to the cwd in the `File` constructor.

``` js
File.paths === {
    base      : '/Users/timrwood/includer', // added for free
    Scriptsrc : '/Users/timrwood/includer/Script/src',
    baz       : '/Users/timrwood/includer/test/fixtures/pathMapping/B',
    aboveCwd  : '/Users/timrwood/other'
};
```

Then, if someone wants the base to be something other than cwd, then can change it in the paths config.

``` js
includer(file, {
  paths : {
    base : '../other-base',
  }
}, cb);

File.paths === {
  base : '/Users/timrwood/other-base'
};
```

This way, the `include('@base/whatever')` looks and behaves the same way as `include('@userDefined/whatever')`.

Also, because `:base` is now just another configurable `@base` path alias, there isn't really a need for `baseUrl` anymore.

**Comment by timrwood** [comment]
An implementation might look something like this.

``` js
function File(opts) {
    this.opts = opts;
    this._seen = {};

    this.paths = {
        base : path.resolve()
    };

    if (this.opts.paths) {
        this.resolvePaths(this.opts.paths);
    }

    if (this.opts.separator) {
        this.separator = this.opts.separator;
    }
}

File.prototype.resolvePaths = function (paths) {
    var resolved = this.paths;
    Object.keys(paths).forEach(function (key) {
        resolved[key] = path.resolve(paths[key]);
    });
}
```

Then, your `node.file.substituteMappings` can probably stay as is, and we can remove the `if (matchPath.substr(0, 5) === ':base') {...}` bit.

**Comment by timrwood** [comment]
As far as testing goes, we could probably switch to something like this.

https://github.com/ff0000/red-sass/blob/master/test/test.js#L15-L21

Rather than testing the files wholesale, we can just split on newlines (`/\n|\r\n/g` maybe), filter out whitespace only lines, and compare those arrays.

**Comment by isochronous** [comment]
I like all of those suggestions, but unfortunately I'm going to be out of town until Monday, so it'll be a few days until I can work on this. If you want, you can create another branch, I'll submit the pull request to the new branch instead of master, then you can accept it and make any changes you feel like without disturbing master... Or just wait. Whatever :)

**Comment by timrwood** [comment]
@isochronous, I merged it into another branch manually, made those changes, and opened another PR.

Let me know what you think at #12.

**Pull request closed without merging**
